In [13]:
import pandas as pd
import numpy as np
from numpy import array
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional

In [2]:
colnames = ['Pulse Number', 'Brightness', 'Uncertainty']
pulsar6 = pd.read_csv("Data/J1644-4559.pulses", sep = ' ', header = None, names = colnames)

In [3]:
pulsar6.head()

Pulse Number  Brightness  Uncertainty
0             1    0.634671     0.002761
1             2    0.736945     0.005207
2             3    0.693834     0.002706
3             4    1.021866     0.010184
4             5    0.673845     0.006236

In [4]:
brightness = list(pulsar6['Brightness'])
brightness

[0.6346714,
 0.7369454,
 0.6938341,
 1.021866,
 0.6738453,
 0.6768825,
 0.5270392,
 0.6734173,
 0.3570756,
 0.6617037,
 0.5455637,
 0.4946546,
 0.8042599,
 0.5133624,
 0.4770252,
 0.3995709,
 0.1880686,
 0.7485923,
 0.723437,
 0.960154,
 0.7077145,
 1.07455,
 0.9613396,
 0.7544566,
 0.7731512,
 0.6326247,
 0.9491536,
 0.5976236,
 0.5358455,
 0.4823253,
 0.007641718,
 0.3384609,
 0.4226295,
 0.4172967,
 0.4866613,
 0.474994,
 0.2820107,
 0.5241109,
 0.7348035,
 0.7454862,
 0.7803042,
 0.9990716,
 0.6589876,
 0.7188401,
 0.6039976,
 0.7266428,
 0.5741913,
 0.7266481,
 0.6223379,
 0.5905332,
 0.5636434,
 0.6927038,
 0.6748244,
 0.4850771,
 0.5154094,
 0.4861331,
 0.7445553,
 0.8274334,
 0.5971083,
 0.9172228,
 0.7009897,
 0.5611873,
 0.755055,
 0.548961,
 0.4883782,
 0.5705138,
 0.6909211,
 0.7797759,
 0.7110825,
 0.9880999,
 0.6565107,
 0.4854965,
 0.7354586,
 0.9091333,
 0.7606739,
 0.6818882,
 0.5743544,
 0.3454394,
 0.6301639,
 0.6635159,
 0.5985485,
 0.3900236,
 0.5116962,
 0.4355926

In [14]:
def split_list(blist, steps):
    X, y = list(), list()
    for i in range(len(blist)):
        # find the end of this pattern
        end_ix = i + steps
        # check if we are beyond the sequence
        if end_ix > len(blist)-1:
            break
        # gather input and output parts of the pattern
        list_x, list_y = blist[i:end_ix], blist[end_ix]
        X.append(list_x)
        y.append(list_y)
    return array(X), array(y)

In [15]:
X, y = split_list(brightness, 25)
X

array([[0.6346714, 0.7369454, 0.6938341, ..., 0.9613396, 0.7544566,
        0.7731512],
       [0.7369454, 0.6938341, 1.021866 , ..., 0.7544566, 0.7731512,
        0.6326247],
       [0.6938341, 1.021866 , 0.6738453, ..., 0.7731512, 0.6326247,
        0.9491536],
       ...,
       [0.6833293, 0.6304144, 0.6704538, ..., 0.6237565, 0.7760831,
        0.6253823],
       [0.6304144, 0.6704538, 0.7173298, ..., 0.7760831, 0.6253823,
        0.6475589],
       [0.6704538, 0.7173298, 0.5334357, ..., 0.6253823, 0.6475589,
        0.3124493]])

In [16]:
X = X.reshape((X.shape[0], X.shape[1], 1))
X

array([[[0.6346714],
        [0.7369454],
        [0.6938341],
        ...,
        [0.9613396],
        [0.7544566],
        [0.7731512]],

       [[0.7369454],
        [0.6938341],
        [1.021866 ],
        ...,
        [0.7544566],
        [0.7731512],
        [0.6326247]],

       [[0.6938341],
        [1.021866 ],
        [0.6738453],
        ...,
        [0.7731512],
        [0.6326247],
        [0.9491536]],

       ...,

       [[0.6833293],
        [0.6304144],
        [0.6704538],
        ...,
        [0.6237565],
        [0.7760831],
        [0.6253823]],

       [[0.6304144],
        [0.6704538],
        [0.7173298],
        ...,
        [0.7760831],
        [0.6253823],
        [0.6475589]],

       [[0.6704538],
        [0.7173298],
        [0.5334357],
        ...,
        [0.6253823],
        [0.6475589],
        [0.3124493]]])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.20)

In [37]:
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(25, 1)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [38]:
history = model.fit(X, y, validation_split=0.33, epochs=200, verbose=0, batch_size=10)

In [39]:
y_pred = model.predict(X_test, verbose=0)
y_pred

array([[0.5148085 ],
       [0.70290655],
       [0.67805773],
       [0.71877366],
       [0.6302616 ],
       [0.64889514],
       [0.6785667 ],
       [0.68087935],
       [0.6812609 ],
       [0.75224024],
       [0.6515616 ],
       [0.5444365 ],
       [0.72644883],
       [0.767894  ],
       [0.60004205],
       [0.6575062 ],
       [0.6788362 ],
       [0.6788802 ],
       [0.49974063],
       [0.7252505 ],
       [0.6607562 ],
       [0.6179061 ],
       [0.6055599 ],
       [0.6356569 ],
       [0.5807221 ],
       [0.7693698 ],
       [0.66253114],
       [0.60806334],
       [0.6060945 ],
       [0.65913117],
       [0.60062385],
       [0.65090704],
       [0.6076019 ],
       [0.6280531 ],
       [0.6900202 ],
       [0.72474617],
       [0.6601911 ],
       [0.7530977 ],
       [0.6178819 ],
       [0.717069  ],
       [0.68122256],
       [0.591723  ],
       [0.7347556 ],
       [0.3423583 ],
       [0.5944687 ],
       [0.5176849 ],
       [0.7625614 ],
       [0.760

In [40]:
model.evaluate(X_test, y_test)

5/5 [==============================] - 0s 4ms/step - loss: 0.6245 - accuracy: 0.0000e+00


[0.6245484948158264, 0.0]

In [41]:
# MLP with automatic validation set
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy
# fix random seed for reproducibility
numpy.random.seed(7)
# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X, Y, validation_split=0.33, epochs=150, batch_size=10)

OSError: pima-indians-diabetes.csv not found.