In [43]:
import pandas as pd
import numpy as np
from numpy import array
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional

In [44]:
colnames = ['Pulse Number', 'Brightness', 'Uncertainty']
pulsar6 = pd.read_csv("Data/J1644-4559.pulses", sep = ' ', header = None, names = colnames)

In [45]:
pulsar6.head()

Pulse Number  Brightness  Uncertainty
0             1    0.634671     0.002761
1             2    0.736945     0.005207
2             3    0.693834     0.002706
3             4    1.021866     0.010184
4             5    0.673845     0.006236

In [46]:
brightness = pulsar6[['Brightness', 'Uncertainty']].values.tolist()
brightness

[[0.6346714, 0.002760888],
 [0.7369454, 0.005207055],
 [0.6938341, 0.0027059],
 [1.021866, 0.01018372],
 [0.6738453, 0.006235539],
 [0.6768825, 0.004762893],
 [0.5270392, 0.002422239],
 [0.6734173, 0.003174072],
 [0.3570756, 0.00284815],
 [0.6617037, 0.005587867],
 [0.5455637, 0.00383466],
 [0.4946546, 0.003145323],
 [0.8042599, 0.005257828],
 [0.5133624, 0.005700175],
 [0.4770252, 0.002944893],
 [0.3995709, 0.00471191],
 [0.1880686, 0.002452335],
 [0.7485923, 0.005467613],
 [0.723437, 0.00454828],
 [0.960154, 0.006764586],
 [0.7077145, 0.006010729],
 [1.07455, 0.006830858],
 [0.9613396, 0.006616562],
 [0.7544566, 0.004116521],
 [0.7731512, 0.004920349],
 [0.6326247, 0.004571389],
 [0.9491536, 0.007181743],
 [0.5976236, 0.00354048],
 [0.5358455, 0.00544293],
 [0.4823253, 0.004531542],
 [0.007641718, 0.002129179],
 [0.3384609, 0.00354179],
 [0.4226295, 0.003680959],
 [0.4172967, 0.003833883],
 [0.4866613, 0.003875858],
 [0.474994, 0.00441279],
 [0.2820107, 0.002753933],
 [0.5241109, 0.0

In [88]:
from sklearn import preprocessing

brightness = preprocessing.normalize(brightness)

brightness[:10]

array([[0.99999054, 0.00435007],
       [0.99997504, 0.00706555],
       [0.9999924 , 0.00389989],
       [0.99995035, 0.00996531],
       [0.99995719, 0.00925327],
       [0.99997524, 0.00703634],
       [0.99998944, 0.00459589],
       [0.99998889, 0.00471333],
       [0.99996819, 0.00797607],
       [0.99996435, 0.00844437]])

In [89]:
def split_list(blist, steps):
    X, y = list(), list()
    for i in range(len(blist)):
        # find the end of this pattern
        end_ix = i + steps
        # check if we are beyond the sequence
        if end_ix > len(blist)-1:
            break
        # gather input and output parts of the pattern
#         print(blist)
        list_x, list_y = blist[i:end_ix], blist[end_ix][0]
        X.append(list_x)
        y.append(list_y)
    return array(X), array(y)

In [90]:
X, y = split_list(brightness, 25)
y

array([0.99997389, 0.99997138, 0.99998245, 0.99994842, 0.99995587,
       0.96330697, 0.99994525, 0.99996207, 0.9999578 , 0.99996829,
       0.99995685, 0.99995232, 0.99995463, 0.99998779, 0.99997114,
       0.99999128, 0.99999419, 0.99999315, 0.99998042, 0.9999891 ,
       0.99991952, 0.99991489, 0.99998935, 0.9999896 , 0.99997707,
       0.99998497, 0.99999445, 0.99999227, 0.99998492, 0.99998723,
       0.99998774, 0.99997637, 0.99999306, 0.99999021, 0.99999365,
       0.99999188, 0.99997954, 0.99999265, 0.99998595, 0.99994828,
       0.99992542, 0.99994963, 0.99999   , 0.99998175, 0.99999172,
       0.9999578 , 0.99997405, 0.99996857, 0.9999511 , 0.99997486,
       0.99996872, 0.99998509, 0.99996479, 0.99999102, 0.99997387,
       0.9999905 , 0.99997678, 0.99992867, 0.99996135, 0.99996511,
       0.99987659, 0.99998377, 0.99998898, 0.99996173, 0.99997964,
       0.99992309, 0.9999942 , 0.99993293, 0.99997658, 0.9999931 ,
       0.99998132, 0.99998118, 0.99997509, 0.99995652, 0.99995

In [91]:
X = X.reshape((X.shape[0], X.shape[1], 2))
X

array([[[0.99999054, 0.00435007],
        [0.99997504, 0.00706555],
        [0.9999924 , 0.00389989],
        ...,
        [0.99997632, 0.00688248],
        [0.99998511, 0.00545619],
        [0.99997975, 0.00636389]],

       [[0.99997504, 0.00706555],
        [0.9999924 , 0.00389989],
        [0.99995035, 0.00996531],
        ...,
        [0.99998511, 0.00545619],
        [0.99997975, 0.00636389],
        [0.99997389, 0.00722588]],

       [[0.9999924 , 0.00389989],
        [0.99995035, 0.00996531],
        [0.99995719, 0.00925327],
        ...,
        [0.99997975, 0.00636389],
        [0.99997389, 0.00722588],
        [0.99997138, 0.00756625]],

       ...,

       [[0.99995624, 0.00935541],
        [0.9999733 , 0.00730773],
        [0.99995598, 0.00938235],
        ...,
        [0.99994432, 0.01055212],
        [0.99993384, 0.01150305],
        [0.99995371, 0.00962188]],

       [[0.9999733 , 0.00730773],
        [0.99995598, 0.00938235],
        [0.99997405, 0.00720472],
        .

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.20)

In [93]:
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(25, 2)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [94]:
history = model.fit(X, y, validation_split=0.33, epochs=50, verbose=1, batch_size=10)

Epoch 1/50
45/45 [==============================] - 2s 13ms/step - loss: 0.3463 - accuracy: 0.0000e+00 - val_loss: 0.0237 - val_accuracy: 0.0000e+00
Epoch 2/50
45/45 [==============================] - 0s 8ms/step - loss: 0.0484 - accuracy: 0.0000e+00 - val_loss: 8.8191e-04 - val_accuracy: 0.0000e+00
Epoch 3/50
45/45 [==============================] - 0s 7ms/step - loss: 0.0013 - accuracy: 0.0000e+00 - val_loss: 3.7745e-04 - val_accuracy: 0.0000e+00
Epoch 4/50
45/45 [==============================] - 0s 7ms/step - loss: 0.0012 - accuracy: 0.0000e+00 - val_loss: 4.0175e-04 - val_accuracy: 0.0000e+00
Epoch 5/50
45/45 [==============================] - 0s 6ms/step - loss: 0.0012 - accuracy: 0.0000e+00 - val_loss: 4.2571e-04 - val_accuracy: 0.0000e+00
Epoch 6/50
45/45 [==============================] - 0s 6ms/step - loss: 0.0012 - accuracy: 0.0000e+00 - val_loss: 3.8442e-04 - val_accuracy: 0.0000e+00
Epoch 7/50
45/45 [==============================] - 0s 7ms/step - loss: 0.0012 - accuracy: 

In [95]:
y_pred = model.predict(X_test, verbose=0)
y_pred

array([[0.9999403 ],
       [0.9999407 ],
       [0.99994016],
       [0.9999414 ],
       [0.99994034],
       [0.99994016],
       [0.9999398 ],
       [0.9999397 ],
       [0.99994195],
       [0.99994206],
       [0.9999398 ],
       [0.99993944],
       [0.9999405 ],
       [0.9999387 ],
       [0.9999397 ],
       [0.9999423 ],
       [0.9999411 ],
       [0.9999403 ],
       [0.9999409 ],
       [0.999943  ],
       [0.9999402 ],
       [0.9999398 ],
       [0.99993896],
       [0.99994206],
       [0.9999406 ],
       [0.9999398 ],
       [0.9999405 ],
       [0.99994063],
       [0.9999415 ],
       [0.9999389 ],
       [0.9999381 ],
       [0.9999428 ],
       [0.999941  ],
       [0.9999411 ],
       [0.99994075],
       [0.9999428 ],
       [0.99994016],
       [0.9999403 ],
       [0.99995327],
       [0.99993986],
       [0.99994004],
       [0.9999398 ],
       [0.99994147],
       [0.99993885],
       [0.99993885],
       [0.9999402 ],
       [0.9999398 ],
       [0.999

In [96]:
model.evaluate(X_test, y_test)

5/5 [==============================] - 0s 4ms/step - loss: 3.1127e-04 - accuracy: 0.0000e+00


[0.0003112679114565253, 0.0]